### ISSUE TITLE
About Oxford5k and paris6k dataset

### ISSUE THREAD

**Issue by Peanut736** [Rohit102497/MABNet#1]
Hi~Can you offer the train and test datasets about oxford5k paris6k?

**Comment by Peanut736** [comment]
ok, i know. Train on Google Landmarks Dataset, test on Oxford5k and Paris6k?

**Comment by Rohit102497** [comment]
Yes, Oxford and Paris are only for testing and the models are trained on Google Landmarks.

**Comment by Peanut736** [comment]
Can you offer the trained models on Google Landmarks?

**Comment by Peanut736** [comment]
@Rohit102497 
Can you offer the trained models on Google Landmarks?

**Comment by Luckygyana** [comment]
we'll share the weights soon.

**Comment by ChengHuan2020** [comment]
Hello, did you receive the pre-trained model from an author?

**Comment by Peanut736** [comment]
Sorry, i didt receive





------------------ Original ------------------
From: A student ***@***.***&gt;
Date: Wed,Apr 26,2023 2:48 PM
To: Rohit102497/MABNet ***@***.***&gt;
Cc: Peanut736 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Rohit102497/MABNet] About Oxford5k and paris6k dataset (Issue#1)





 
Hello, did you receive the pre-trained model from an author?

**Comment by Rohit102497** [comment]
Hello @ChengHuan2020 and @Peanut736 , to share the trained model we need to retrain it. But, due to computational constraints and other deadlines, we are unable to do it right now. Rest assured, we will soon share the trained models.
